version: "3.4"

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: env
    volumes:
      - ./app:/app # Mount source code inside the container.
    working_dir: /app
    command: ["go", "run", "main.go"]
